CREATE TABLE IF NOT EXISTS `buzzads`.`ad_order_category` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
   `PARENT_ID` int(11) NOT NULL,
   `NAME` varchar(100) DEFAULT NULL,
   `NAME_EN` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PARENT_ID_IDX` (`PARENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `buzzads`.`ad_order_category` VALUES
('1', '0', '文化娱乐', 'Arts & Entertainment'),
('2', '0', '教育培训', 'Jobs & Education'),
('3', '0', '游戏', 'Games'),
('4', '0', '消费数码', 'Consumer Electronics'),
('5', '0', '健康医疗', 'Health & Wellness'),
('6', '0', '美容及化妆品', 'Beauty & Cosmetics'),
('7', '0', '汽车', 'Automobiles'),
('8', '0', '运动健身', 'Sports & Fitness'),
('9', '0', 'IT及信息产业', 'Internet & Technology'),
('10', '0', '母婴育儿', 'Baby & Maternity'),
('11', '0', '金融财经', 'Personal Finance'),
('12', '0', '咨询及服务', 'Consulting & Services'),
('13', '0', '工业', 'Business & Industrial'),
('14', '0', '女性时尚', 'Female Fashion'),
('15', '0', '旅游商旅', 'Leisure Travel & Business Travel'),
('16', '0', '食品美食', 'Food & Drink'),
('17', '0', '家居生活', 'Home & Lifestyle'),
('18', '0', '房地产及建筑', 'Real Estate & Construction'),
('19', '0', '办公用品', 'Office Equipment'),
('20', '0', '农业', 'Agriculture'),
('21', '0', '烟酒', 'Tobacco & Alcohol'),
('22', '0', '时政与财经', 'Politics & Finance'),
('23', '1', '娱乐综艺', 'Variety & Entertainment'),
('24', '1', '院线电影', 'Movies'),
('25', '1', '网络影视剧', 'TV Dramas'),
('26', '1', '动画漫画', 'Comics & Animation'),
('27', '1', '网络小说', 'Online Literature'),
('28', '1', '文化文学', 'Culture/Literature'),
('29', '1', '书刊杂志', 'Books/Magazines'),
('30', '1', '高雅音乐', 'Classical Music & Jazz'),
('31', '1', '流行音乐', 'Pop Music'),
('32', '1', '音响器材', 'Audio Equipment'),
('33', '1', '乐器', 'Musical Instruments'),
('34', '1', '人文艺术', 'Humanities & Arts'),
('35', '1', '其他', 'Others'),
('36', '2', '初级中级教育', 'Primary & Secondary Schooling'),
('37', '2', '学历与留学', 'Overseas Education'),
('38', '2', 'MBA', 'MBA'),
('39', '2', '职业技能培训', 'Vocational & Continuing Education'),
('40', '2', '其他', 'Others'),
('41', '3', '大型客户端游戏', 'Massive Multiplayer'),
('42', '3', '网页游戏', 'Online Games'),
('43', '3', '手机平板游戏', 'Mobile Phone/Tablet Games'),
('44', '3', '小游戏Flash游戏', 'Mini Games & Flash Games'),
('45', '3', '电子竞技', 'Sports Games'),
('46', '3', '其他', 'Others'),
('47', '4', '摄影摄像', 'Photography & Videography'),
('48', '4', '电玩', 'Video Games'),
('49', '4', '手机平板与应用', 'Mobile Phones/Tablets & Apps'),
('50', '4', '硬件及网络', 'Hardware & Networking'),
('51', '4', '家电', 'Home Appliances'),
('52', '4', '其他', 'Others'),
('53', '5', '情感心理', 'Psychology'),
('54', '5', '整形整容', 'Cosmetic Procedures'),
('55', '5', '保健养生', 'Healthcare'),
('56', '5', '医疗', 'Medical Treatment'),
('57', '6', '护肤', 'Skin Care'),
('58', '6', '洗护日用', 'Daily Personal Care'),
('59', '6', '彩妆', 'Make-Up/Cosmetics'),
('60', '7', '高档汽车', 'Luxury Cars'),
('61', '7', '中档汽车', 'Mid-End Cars'),
('62', '7', '入门级汽车', 'Entry-Level Cars'),
('63', '7', '养车用车', 'Vehicle Maintenance'),
('64', '7', '二手车', 'Used Cars'),
('65', '7', '汽车租赁', 'Rental Cars'),
('66', '7', '汽车制造商', 'Car Manufacturers'),
('67', '7', '汽车保险', 'Auto Insurance'),
('68', '7', '汽车周边', 'Auto Accessories'),
('69', '7', '其他', 'Others'),
('70', '8', '运动', 'Sports'),
('71', '8', '健身', 'Fitness'),
('72', '8', '户外', 'Outdoor Sports'),
('73', '8', '其他', 'Others'),
('74', '9', '电信、通信服务', 'Telecommunications/Services'),
('75', '9', '软件', 'Software'),
('76', '10', '婴幼', 'Baby'),
('77', '10', '母婴用品', 'Maternity & Parenting'),
('78', '10', '童书阅读', 'Baby Books'),
('79', '11', '保险', 'Insurance'),
('80', '11', '投资理财', 'Investing'),
('81', '11', '其他', 'Others'),
('82', '12', '婚庆', 'Wedding Services'),
('83', '12', '健身娱乐', 'Health & Fitness Services'),
('84', '14', '服装', 'Clothing'),
('85', '14', '首饰饰品', 'Jewelry/Accessories'),
('86', '14', '奢侈品', 'Designers & Collections'),
('87', '14', '鞋包', 'Shoes & Bags'),
('88', '14', '化妆造型', 'Make-Up & Cosmetics'),
('89', '15', '酒店', 'Hotels & Accommodations'),
('90', '15', '旅游', 'Leisure Travel'),
('91', '15', '航空', 'Air Travel'),
('92', '15', '旅行社', 'Travel Agencies & Services'),
('93', '16', '烹饪和菜谱', 'Cooking & Recipes'),
('94', '16', '休闲食品', 'Snacks'),
('95', '16', '餐馆美食', 'Restaurants'),
('96', '16', '其他', 'Others'),
('97', '18', '开发商', 'Property Development'),
('98', '18', '中介代理', 'Real Estate Agencies'),
('99', '18', '物业管理', 'Property Management'),
('100', '18', '楼盘', 'Real Estate'),
('101', '18', '其他', 'Others'),
('102', '21', '洋酒', 'Liquor & Spirits'),
('103', '21', '红酒、白葡萄酒、香槟', 'Wine/Beer/Champagne'),
('104', '21', '国酒', 'Chinese Liquor/Spirits');


ALTER TABLE `recharge_alipay_record`
DROP `POUNDAGE`,
DROP `RECHARGE_AMOUNT`;


ALTER TABLE  `ad_entry` CHANGE  `SIZE`  `SIZE` INT( 11 ) NULL DEFAULT NULL COMMENT '广告大小';