-- Adjust field type
ALTER TABLE  `ad_detail_cps` 
CHANGE  `ID`  `ID` INT NOT NULL AUTO_INCREMENT COMMENT  '主键',
CHANGE  `ADORDER_ID`  `ADORDER_ID` INT NOT NULL COMMENT  '广告订单ID',
CHANGE  `ADENTRY_ID`  `ADENTRY_ID` INT NOT NULL COMMENT  '广告ID',
CHANGE  `STATUS`  `STATUS` TINYINT NOT NULL COMMENT  'CPS状态，0-未确认，1-已确认',
CHANGE  `PUB_COMMISSION`  `PUB_COMMISSION` INT NOT NULL COMMENT  'CPS站长佣金，即我们发放给站长的佣金',
CHANGE  `COMMISSION`  `COMMISSION` INT NOT NULL COMMENT  'CPS佣金总额，即我们得到的佣金',
CHANGE  `TOTAL_PRICE`  `TOTAL_PRICE` INT NOT NULL COMMENT  'CPS订单总额';

ALTER TABLE  `ad_entry` 
CHANGE  `ID`  `ID` INT NOT NULL AUTO_INCREMENT ,
CHANGE  `ORDER_ID`  `ORDER_ID` INT NOT NULL COMMENT  '广告订单ID';

ALTER TABLE  `ad_order` 
CHANGE  `ID`  `ID` INT NOT NULL AUTO_INCREMENT COMMENT  '订单ID';

ALTER TABLE  `operation_log` 
CHANGE  `ID`  `ID` INT NOT NULL AUTO_INCREMENT COMMENT  '递增主键';

ALTER TABLE  `publisher_contact_info` 
CHANGE  `USER_ID`  `USER_ID` BIGINT NOT NULL COMMENT  '站长USERID';

ALTER TABLE  `publisher_payment` 
CHANGE  `ID`  `ID` INT NOT NULL AUTO_INCREMENT COMMENT  '主键',
CHANGE  `USER_ID`  `USER_ID` INT( 20 ) NOT NULL COMMENT  '站长用户ID',
CHANGE  `AMOUNT`  `AMOUNT` INT NOT NULL DEFAULT  '0' COMMENT  '应付金额',
CHANGE  `FEE`  `FEE` INT NOT NULL DEFAULT  '0' COMMENT  '手续费',
CHANGE  `TAX`  `TAX` INT NOT NULL DEFAULT  '0' COMMENT  '税',
CHANGE  `PAID`  `PAID` INT NOT NULL DEFAULT  '0' COMMENT  '实付金额';

ALTER TABLE  `publisher_settlement` 
CHANGE  `ID`  `ID` INT NOT NULL AUTO_INCREMENT COMMENT  '主键',
CHANGE  `USER_ID`  `USER_ID` INT( 20 ) NOT NULL COMMENT  '站长用户ID',
CHANGE  `CPS_COMMISSION`  `CPS_COMMISSION` INT NOT NULL DEFAULT  '0' COMMENT  'CPS站长佣金（已确认CPS）',
CHANGE  `CPC_COMMISSION`  `CPC_COMMISSION` INT NOT NULL DEFAULT  '0' COMMENT  'CPC站长佣金',
CHANGE  `COMMISSION`  `COMMISSION` INT NOT NULL DEFAULT  '0' COMMENT  '佣金总额',
CHANGE  `PAYMENT_ID`  `PAYMENT_ID` INT NULL DEFAULT NULL COMMENT  '支付记录ID';

ALTER TABLE `stats_admin_daily` 
CHANGE `ID` `ID` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键', 
CHANGE `VIEWS` `VIEWS` INT NOT NULL DEFAULT '0' COMMENT '广告浏览数', 
CHANGE `CLICKS` `CLICKS` INT NOT NULL DEFAULT '0' COMMENT '广告点击数', 
CHANGE `CPC_PUB_COMMISSION` `CPC_PUB_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPC站长佣金，即我们发放给站长的佣金', 
CHANGE `CPC_TOTAL_COMMISSION` `CPC_TOTAL_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPC佣金总额，即我们得到的佣金', 
CHANGE `CPS_CONFIRMED_COMMISSION` `CPS_CONFIRMED_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS站长实际佣金，即已确认的CPS佣金', 
CHANGE `CPS_PUB_COMMISSION` `CPS_PUB_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS站长预期佣金，包括已确认和未确认的CPS佣金', 
CHANGE `CPS_TOTAL_CONFIRMED_COMMISSION` `CPS_TOTAL_CONFIRMED_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS实际收入', 
CHANGE `CPS_TOTAL_COMMISSION` `CPS_TOTAL_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS佣金总额，即我们得到的佣金', 
CHANGE `CPS_TOTAL_PRICE` `CPS_TOTAL_PRICE` INT NOT NULL DEFAULT '0' COMMENT 'CPS总订单金额';

ALTER TABLE `stats_ad_daily` 
CHANGE `ID` `ID` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键', 
CHANGE `ADENTRY_ID` `ADENTRY_ID` INT NOT NULL COMMENT '广告ID', 
CHANGE `ADORDER_ID` `ADORDER_ID` INT NOT NULL COMMENT '广告订单ID', 
CHANGE `VIEWS` `VIEWS` INT NOT NULL DEFAULT '0' COMMENT '广告浏览数', 
CHANGE `CLICKS` `CLICKS` INT NOT NULL DEFAULT '0' COMMENT '广告点击数', 
CHANGE `CPC_PUB_COMMISSION` `CPC_PUB_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPC站长佣金，即我们发放给站长的佣金', 
CHANGE `CPC_TOTAL_COMMISSION` `CPC_TOTAL_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPC佣金总额，即我们得到的佣金', 
CHANGE `CPS_CONFIRMED_COMMISSION` `CPS_CONFIRMED_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS站长实际佣金，即已确认的CPS佣金', 
CHANGE `CPS_PUB_COMMISSION` `CPS_PUB_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS站长佣金，即我们发放给站长的佣金', 
CHANGE `CPS_TOTAL_CONFIRMED_COMMISSION` `CPS_TOTAL_CONFIRMED_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS实际收入', 
CHANGE `CPS_TOTAL_COMMISSION` `CPS_TOTAL_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS佣金总额，即我们得到的佣金', 
CHANGE `CPS_TOTAL_PRICE` `CPS_TOTAL_PRICE` INT NOT NULL DEFAULT '0' COMMENT 'CPS总订单金额';

ALTER TABLE `stats_publisher_daily` 
CHANGE `ID` `ID` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键', 
CHANGE `VIEWS` `VIEWS` INT NOT NULL DEFAULT '0' COMMENT '广告浏览数', 
CHANGE `CLICKS` `CLICKS` INT NOT NULL DEFAULT '0' COMMENT '广告点击数', 
CHANGE `CPC_PUB_COMMISSION` `CPC_PUB_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPC站长佣金，即我们发放给站长的佣金', 
CHANGE `CPC_TOTAL_COMMISSION` `CPC_TOTAL_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPC佣金总额，即我们得到的佣金', 
CHANGE `CPS_CONFIRMED_COMMISSION` `CPS_CONFIRMED_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS站长实际佣金，即已确认的CPS佣金', 
CHANGE `CPS_PUB_COMMISSION` `CPS_PUB_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS站长佣金，即我们发放给站长的佣金', 
CHANGE `CPS_TOTAL_CONFIRMED_COMMISSION` `CPS_TOTAL_CONFIRMED_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS实际收入', 
CHANGE `CPS_TOTAL_COMMISSION` `CPS_TOTAL_COMMISSION` INT NOT NULL DEFAULT '0' COMMENT 'CPS佣金总额，即我们得到的佣金', 
CHANGE `CPS_TOTAL_PRICE` `CPS_TOTAL_PRICE` INT NOT NULL DEFAULT '0' COMMENT 'CPS总订单金额';

-- for advertiser account
CREATE TABLE IF NOT EXISTS `buzzads`.`advertiser_account` (
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `COMPANY_NAME` varchar(50) NOT NULL COMMENT '公司名',
 `WEBSITE_NAME` varchar(50) NOT NULL COMMENT '网站名',
 `WEBSITE_URL` varchar(200) NOT NULL COMMENT '网站URL',
 `BUSINESS_TYPE` tinyint(4) NOT NULL COMMENT '业务类型',
 `STATUS` tinyint(4) NOT NULL COMMENT '状态：0-Normal，1-Frozen',
 PRIMARY KEY (`ADVERTISER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告主帐户信息。';

CREATE TABLE IF NOT EXISTS `buzzads`.`advertiser_contact_info` (
 `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '联系人ID',
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `ADDRESS` varchar(100) NOT NULL COMMENT '地址',
 `EMAIL` varchar(100) NOT NULL COMMENT 'Email',
 `NAME` varchar(50) NOT NULL COMMENT '姓名',
 `MOBILE` varchar(20) NOT NULL COMMENT '手机号码',
 `QQ` varchar(20) NOT NULL COMMENT 'QQ',
 PRIMARY KEY (`ID`),
 KEY `IDX_ADVERTISER` (`ADVERTISER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告主联系人信息。';


-- for ads
CREATE TABLE IF NOT EXISTS `buzzads`.`ad_campaign` (
 `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `NAME` varchar(50) NOT NULL COMMENT '活动名称',
 `STATUS` tinyint(4) NOT NULL COMMENT '活动状态，：0-Ready，1-Enabled，2-Paused，3-Disabled，4-Suspended, 5-Deleted, 6-Verifying, 7-Rejected',
 `NETWORK` tinyint(4) NOT NULL COMMENT '活动网络：0-Lezhi，1-bShare，2-BuzzAds',
 `BID_TYPE` tinyint(4) NOT NULL COMMENT '活动出价类型：0-CPM，1-CPA，2-CPS，3-CPC',
 `START_DATE` date DEFAULT NULL COMMENT '活动开始日期',
 `END_DATE` date DEFAULT NULL COMMENT '活动结束日期',
 `LOCATION` varchar(200) DEFAULT NULL COMMENT '活动位置，以因为逗号分割的省市代号。比如”BJ,SH,TJ”，表示在指定的省份进行投放。',
 `UPDATE_AT` datetime NOT NULL COMMENT '更新时间',
 PRIMARY KEY (`ID`),
 KEY `IDX_ADVERTISER` (`ADVERTISER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告活动信息。';

CREATE TABLE IF NOT EXISTS `buzzads`.`ad_campaign_budget` (
 `CAMPAIGN_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '广告活动ID',
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `DATE_DAY` date NOT NULL COMMENT '当日预算的日期',
 `BUDGET_DAY` bigint(20) NOT NULL DEFAULT '0' COMMENT '当日已使用预算',
 `BUDGET_TOTAL` bigint(20) NOT NULL DEFAULT '0' COMMENT '总的已使用预算',
 `MAX_BUDGET_DAY` bigint(20) NOT NULL DEFAULT '0' COMMENT '最大每日预算，<=0表示没有限制',
 `MAX_BUDGET_TOTAL` bigint(20) NOT NULL DEFAULT '0' COMMENT '最大总预算，<=0表示没有限制',
 PRIMARY KEY (`CAMPAIGN_ID`),
 KEY `IDX_ADVERTISER` (`ADVERTISER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告活动预算统计';


ALTER TABLE  `buzzads`.`ad_order` ADD  `ADVERTISER_ID` INT NOT NULL COMMENT  '广告主ID' AFTER  `ID`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `CAMPAIGN_ID` INT NOT NULL COMMENT  '广告活动ID' AFTER  `ADVERTISER_ID`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `NETWORK` TINYINT NOT NULL COMMENT  '广告网络：0-Lezhi，1-bShare，2-BuzzAds' AFTER  `NAME`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `BID_PRICE` INT NOT NULL COMMENT  '广告出价' AFTER  `NETWORK`;
ALTER TABLE  `buzzads`.`ad_order` CHANGE  `BILLING_TYPE`  `BID_TYPE` TINYINT( 4 ) NOT NULL COMMENT  '支付出价：0-CPM，1-CPA，2-CPS，3-CPC';
ALTER TABLE  `buzzads`.`ad_order` CHANGE  `STATUS`  `STATUS` TINYINT( 4 ) NOT NULL COMMENT '广告订单状态，：0-Ready，1-Enabled，2-Paused，3-Disabled，4-Suspended, 5-Deleted, 6-Verifying, 7-Rejected';
ALTER TABLE  `buzzads`.`ad_order` ADD  `KEYWORDS` VARCHAR( 500 ) DEFAULT NULL COMMENT  '广告的关键词' AFTER  `STATUS`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `START_DATE` DATE DEFAULT NULL COMMENT  '订单开始时间' AFTER  `KEYWORDS`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `END_DATE` DATE DEFAULT NULL COMMENT  '订单结束时间' AFTER  `START_DATE`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `SCHEDULE_DAY` INT NOT NULL DEFAULT  '0' COMMENT  '计划投放日。使用IntegerValuedEnumSetType保存的WeekDay集合，为空则不指定投放日，即每日都可投放。' AFTER  `END_DATE`;
ALTER TABLE  `buzzads`.`ad_order` ADD  `SCHEDULE_TIME` VARCHAR( 100 ) NOT NULL DEFAULT  '' COMMENT  '计划投放时间。包括开始时间和结束时间，例如10:00-18:00。为空则不指定投放时间，即一天24小时都可投放。' AFTER  `SCHEDULE_DAY`;
ALTER TABLE  `buzzads`.`ad_order` ADD INDEX  `IDX_ADVERTISER` (  `ADVERTISER_ID` );
ALTER TABLE  `buzzads`.`ad_order` ADD INDEX  `IDX_CAMPAIGN` (  `CAMPAIGN_ID` );


ALTER TABLE  `buzzads`.`ad_entry` ADD  `ADVERTISER_ID` INT NOT NULL COMMENT  '广告主ID' AFTER  `ID`;
ALTER TABLE  `buzzads`.`ad_entry` ADD  `CAMPAIGN_ID` INT NOT NULL COMMENT  '广告活动ID' AFTER  `ADVERTISER_ID`;
ALTER TABLE  `buzzads`.`ad_entry` CHANGE  `ORDER_ID`  `ORDER_ID` INT( 20 ) NOT NULL COMMENT  '广告订单ID';
ALTER TABLE  `buzzads`.`ad_entry` ADD  `NAME` VARCHAR( 100 ) NOT NULL COMMENT  '广告项名字' AFTER  `ORDER_ID`;
ALTER TABLE  `buzzads`.`ad_entry` ADD  `STATUS` TINYINT NOT NULL COMMENT '广告项状态：0-Ready，1-Enabled，2-Paused，3-Disabled，4-Suspended, 5-Deleted, 6-Verifying, 7-Rejected' AFTER  `NAME`;
ALTER TABLE  `buzzads`.`ad_entry` ADD  `SIZE` INT NOT NULL COMMENT  '广告大小' AFTER  `RESOURCE_URL`;
ALTER TABLE  `buzzads`.`ad_entry` ADD  `DISPLAY_URL` VARCHAR( 100 ) DEFAULT NULL COMMENT  '展示URL' AFTER  `SIZE`;
ALTER TABLE  `buzzads`.`ad_entry` CHANGE  `TITLE`  `TITLE` VARCHAR( 500 ) DEFAULT NULL COMMENT  '广告标题';
ALTER TABLE  `buzzads`.`ad_entry` ADD  `DESCRIPTION` VARCHAR( 500 ) DEFAULT NULL COMMENT  '广告文字' AFTER  `TITLE`;
ALTER TABLE  `buzzads`.`ad_entry` ADD INDEX  `IDX_ADVERTISER` (  `ADVERTISER_ID` );
ALTER TABLE  `buzzads`.`ad_entry` ADD INDEX  `IDX_CAMPAIGN` (  `CAMPAIGN_ID` );
ALTER TABLE  `buzzads`.`ad_entry` ADD INDEX  `IDX_ORDER` (  `ORDER_ID` );


alter table `buzzads`.`stats_publisher_daily` 
   change `PRODUCT` `NETWORK` tinyint(4) NOT NULL comment '来源：0-Lezhi，1-bShare';
alter table `buzzads`.`stats_admin_daily` 
   change `PRODUCT` `NETWORK` tinyint(4) NOT NULL comment '来源：0-Lezhi，1-bShare';
alter table `buzzads`.`stats_ad_daily` 
   change `PRODUCT` `NETWORK` tinyint(4) NOT NULL comment '来源：0-Lezhi，1-bShare';
ALTER TABLE  `buzzads`.`ad_detail_cps` 
CHANGE  `PRODUCT`  `NETWORK` TINYINT( 4 ) NOT NULL COMMENT  '来源：0-Lezhi，1-bShare';

-- for statistics & billing
CREATE TABLE IF NOT EXISTS `buzzads`.`stats_campaign_daily` (
 `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
 `CAMPAIGN_ID` int(11) NOT NULL COMMENT '广告活动ID',
 `DATE_DAY` date NOT NULL COMMENT '统计日期',
 `NETWORK` tinyint(4) NOT NULL COMMENT '广告网络：0-Lezhi，1-bShare，2-BuzzAds',
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `VIEWS` int(11) NOT NULL DEFAULT '0' COMMENT '广告浏览数',
 `CLICKS` int(11) NOT NULL DEFAULT '0' COMMENT '广告点击数',
 `CPC_CLICK_NO` int(11) NOT NULL DEFAULT '0' COMMENT 'CPC有效点击',
 `CPC_PUB_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPC站长佣金，即我们发放给站长的佣金',
 `CPC_TOTAL_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPC佣金总额，即我们得到的佣金',
 `CPS_ORDER_NO` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS订单数',
 `CPS_CONFIRMED_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS站长实际佣金，即已确认的CPS佣金',
 `CPS_PUB_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS站长佣金，即我们发放给站长的佣金',
 `CPS_TOTAL_CONFIRMED_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS实际收入',
 `CPS_TOTAL_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS佣金总额，即我们得到的佣金',
 `CPS_TOTAL_PRICE` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS总订单金额',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `UNQ_UUID_DAY` (`CAMPAIGN_ID`,`DATE_DAY`,`NETWORK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告活动每日数据';

CREATE TABLE IF NOT EXISTS `buzzads`.`stats_order_daily` (
 `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
 `ORDER_ID` int(11) NOT NULL COMMENT '广告组ID',
 `DATE_DAY` date NOT NULL COMMENT '统计日期',
 `NETWORK` tinyint(4) NOT NULL COMMENT '广告网络：0-Lezhi，1-bShare，2-BuzzAds',
 `VIEWS` int(11) NOT NULL DEFAULT '0' COMMENT '广告浏览数',
 `CLICKS` int(11) NOT NULL DEFAULT '0' COMMENT '广告点击数',
 `CPC_CLICK_NO` int(11) NOT NULL DEFAULT '0' COMMENT 'CPC有效点击',
 `CPC_PUB_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPC站长佣金，即我们发放给站长的佣金',
 `CPC_TOTAL_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPC佣金总额，即我们得到的佣金',
 `CPS_ORDER_NO` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS订单数',
 `CPS_CONFIRMED_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS站长实际佣金，即已确认的CPS佣金',
 `CPS_PUB_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS站长佣金，即我们发放给站长的佣金',
 `CPS_TOTAL_CONFIRMED_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS实际收入',
 `CPS_TOTAL_COMMISSION` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS佣金总额，即我们得到的佣金',
 `CPS_TOTAL_PRICE` int(11) NOT NULL DEFAULT '0' COMMENT 'CPS总订单金额',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `UNQ_UUID_DAY` (`ORDER_ID`,`DATE_DAY`,`NETWORK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告活动每日数据';

CREATE TABLE IF NOT EXISTS `buzzads`.`advertiser_billing` (
 `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '递增主键',
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `DATE_DAY` date NOT NULL COMMENT '结帐日起',
 `TYPE` tinyint(4) NOT NULL COMMENT '结帐类型，目前可以是DEBIT_DAY，REFILL_RECHARGE等。',
 `COMMENT` varchar(200) NOT NULL COMMENT '备注，如充值方式、流水号等',
 `DEBITS` int(11) NOT NULL COMMENT '借项，即广告主支出',
 `CREDITS` int(11) NOT NULL COMMENT '信贷，即广告主充值',
 `BALANCE` bigint(20) NOT NULL COMMENT '广告主的余额 ',
 PRIMARY KEY (`ID`),
 UNIQUE  `UNQ_ADVERTISER_DAY_TYPE` (  `ADVERTISER_ID` ,  `DATE_DAY` ,  `TYPE` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告主结帐';


-- data migration
INSERT INTO `buzzads`.`advertiser_account` (`ADVERTISER_ID`, `COMPANY_NAME`, `WEBSITE_NAME`, `WEBSITE_URL`, `BUSINESS_TYPE`, `STATUS`)
    VALUES('21759', '爱德威广告（上海）有限公司', '成果网', 'http://www.chanet.com.cn', '1', '0');
INSERT INTO `buzzads`.`advertiser_contact_info` (`ID`, `ADVERTISER_ID`, `ADDRESS`, `EMAIL`, `NAME`, `MOBILE`, `QQ`)
    VALUES('1', '21759', '上海市延安东路618号东海商业中心2期15层', 'EMAIL', '陈月', '021-64718181-608', '1372269271');
INSERT INTO `buzzads`.`ad_campaign` (`ID`, `ADVERTISER_ID`, `NAME`, `STATUS`, `NETWORK`, `BID_TYPE`, `UPDATE_AT`)
    VALUES('1', '21759', '成果网CPS接入广告', '1', '1', '2',  NOW());
UPDATE `buzzads`.`ad_order` SET `UPDATE_AT` = NOW() , `ADVERTISER_ID` = '21759' , `CAMPAIGN_ID` = '1' , `NETWORK` = '1';
UPDATE `buzzads`.`ad_order` o SET `UPDATE_AT` = NOW(), `KEYWORDS` = (SELECT e.KEYWORDS FROM `buzzads`.`ad_entry` e WHERE e.ORDER_ID = o.ID);
UPDATE `buzzads`.`ad_entry` SET `UPDATE_AT` = NOW() , `ADVERTISER_ID` = '21759' , `CAMPAIGN_ID` = '1', `STATUS` = '1';
UPDATE `buzzads`.`ad_entry` e SET `UPDATE_AT` = NOW(), `NAME` = (SELECT o.NAME FROM `buzzads`.`ad_order` o WHERE o.ID = e.ORDER_ID);

-- ALTER TABLE  `buzzads`.`ad_order` DROP  `SOURCE`;
-- ALTER TABLE  `buzzads`.`ad_entry` DROP  `KEYWORDS`;


CREATE TABLE IF NOT EXISTS `buzzads`.`advertiser_balance` (
 `ADVERTISER_ID` int(11) NOT NULL COMMENT '广告主ID',
 `DEBITS_TOTAL` bigint(20) NOT NULL COMMENT '借项和，即广告主支出和',
 `CREDITS_TOTAL` bigint(20) NOT NULL COMMENT '信贷和，即广告主充值和',
 `BALANCE` bigint(20) NOT NULL COMMENT '广告主的余额 ',
 `UPDATE_AT` datetime NOT NULL COMMENT '更新时间',
 PRIMARY KEY (`ADVERTISER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='广告主余额与支付充值和';


ALTER TABLE  `publisher_settlement` CHANGE  `PAYMENT_ID`  `PAYMENT_ID` INT( 11 ) NOT NULL DEFAULT  '0' COMMENT  '支付记录ID';
ALTER TABLE  `ad_order` CHANGE  `SCHEDULE_TIME`  `SCHEDULE_TIME` VARCHAR( 100 ) NULL DEFAULT NULL 
COMMENT  '计划投放时间。包括开始时间和结束时间，例如10:00-18:00。为空则不指定投放时间，即一天24小时都可投放。';