ALTER TABLE  `publisher_contact_info` ADD  `RECEIVING_BANK_CODE` TINYINT( 2 ) NOT NULL DEFAULT  '99' AFTER  `RECEIVING_BANK`;
ALTER TABLE  `publisher_contact_info` ADD  `FINANCE_TYPE` TINYINT( 1 ) NOT NULL DEFAULT  '9' AFTER  `RECEIVING_BANK_CODE`;

CREATE TABLE `bfa_user_authority` (
  `USER_ID` int(11) NOT NULL COMMENT '用户ID',
  `CHANNEL_TARGET` tinyint(1) NOT NULL DEFAULT '0' COMMENT '媒体定向-1开通，0未开通',
  PRIMARY KEY (`USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `buzzads`.`ad_order`
   change `CHANNELS` `CHANNELS_TARGET` varchar(4096) NULL  comment '媒体定向列表';

ALTER TABLE `buzzads`.`bfp_channel`
   add column `NAME` varchar(1024) NULL COMMENT '媒体名称' after `DOMAIN`;

ALTER TABLE `publisher_settlement`
CHANGE COLUMN `CPM__NO` `CPM_NO`  int(11) NOT NULL DEFAULT 0 COMMENT 'CPM展示' AFTER `CPC_COMMISSION`;

ALTER TABLE `ad_order`
CHANGE COLUMN `FREQUENCY_CAP` `ORDER_FREQUENCY`  int(10) NOT NULL DEFAULT 0 COMMENT '广告组向单个用户展示的次数频次上限' AFTER `CHANNELS_TARGET`,
ADD COLUMN `ENTRY_FREQUENCY`  int(10) NOT NULL DEFAULT 0 COMMENT '广告向单个用户展示的次数频次上限' AFTER `ORDER_FREQUENCY`;

ALTER TABLE  `publisher_contact_info` CHANGE  `FINANCE_TYPE`  `FINANCE_TYPE` TINYINT( 1 ) NOT NULL DEFAULT  '1'
