
ALTER TABLE `advertiser_billing` DROP `DATE_DAY`;

ALTER TABLE `advertiser_billing` DROP INDEX `UNQ_ADVERTISER_DAY_TYPE`;

ALTER TABLE `advertiser_billing` ADD `UPDATE_AT` DATETIME NOT NULL;

ALTER TABLE  `publisher_settlement` ADD  `COMM_UPDATE_DAY` DATE NOT NULL;

ALTER TABLE  `advertiser_billing` CHANGE  `COMMENT`  `COMMENT` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '备注，如充值方式、流水号等';

CREATE TABLE IF NOT EXISTS `buzzads`.`payment_order_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ORDER_NO` varchar(32) NOT NULL,
  `PRODUCT_TYPE` tinyint(1) NOT NULL,
  `UNIT_PRICE` int(11) NOT NULL,
  `AMOUNT_MONTH` tinyint(4) NOT NULL,
  `TOTAL_FEE` int(11) NOT NULL,
  `ORDER_TIME` datetime NOT NULL,
  `ORDER_STATUS` tinyint(4) DEFAULT NULL,
  `PAYMENT_PLATFORM` tinyint(4) DEFAULT NULL,
  `OUT_TRADE_NO` varchar(64) DEFAULT NULL,
  `PAID_TIME` datetime DEFAULT NULL,
  `SEND_EMAIL` tinyint(1) DEFAULT '0',
  `DATE_START` date DEFAULT NULL,
  `DATE_END` date DEFAULT NULL,
  `REMARK` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ORDER_NO_UNIQUE` (`ORDER_NO`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `buzzads`.`recharge_operate_his` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPERATE_TYPE` tinyint(1) NOT NULL,
  `RECORD_ID` int(11) NOT NULL,
  `ADVERTISER_ID` int(11) NOT NULL,
  `INSERT_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `buzzads`.`recharge_alipay_record` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RECORD_ID` int(11) NOT NULL,
  `ADVERTISER_ID` int(11) NOT NULL,
  `POUNDAGE` VARCHAR( 4 ) NOT NULL,
  `TOTAL_FEE` int(11) NOT NULL DEFAULT '0',
  `TRADE_NO` varchar(100) DEFAULT '',
  `TRADE_STATUS` int(11) NOT NULL DEFAULT '0',
  `CREATE_TIME` datetime NOT NULL,
  `PAYMENT_TIME` datetime NOT NULL,
  `ALI_TRADE_NO` varchar(100) DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `recharge_alipay_record` ADD `RECHARGE_AMOUNT` INT( 11 ) NOT NULL;

CREATE TABLE IF NOT EXISTS `buzzads`.`admin_adjustment` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADMIN_ID` int(11) NOT NULL,
  `RECEIVER_ID` int(11) NOT NULL,
  `RECEIVE_AMOUNT` int(11) NOT NULL DEFAULT '0',
  `REASON` varchar(100) DEFAULT '',
  `DETAIL` varchar(500) DEFAULT '',
  `UPDATE_TIME` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;