
CREATE TABLE `bfp_channel` (
  `ID` int(12) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `DOMAIN` varchar(128) NOT NULL COMMENT '存放域名',
  `UUID` binary(16) NOT NULL,
  `CHANNEL_LEVEL` tinyint(1) NOT NULL COMMENT '媒体类别：1为一级媒体，2为二级媒体',
  `CHANNEL_TYPE` tinyint(3) NOT NULL COMMENT '媒体类型',
  `NETWORK` tinyint(1) NOT NULL COMMENT '投放网络:LEZHI(0), BSHARE(1), BUZZADS(2), WJF(3);',
  `AD_TYPE` tinyint(1) DEFAULT NULL COMMENT '广告位类型:1为文字，2为图文',
  `OPEN_TIME` datetime DEFAULT NULL COMMENT '媒体开启时间',
  `CLOSE_TIME` datetime DEFAULT NULL COMMENT '媒体关闭时间',
  `MIN_CPM` int(10) NOT NULL COMMENT '最低cpm单价',
  `AD_THUMB` varchar(256) NOT NULL COMMENT '广告位截图URL',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BFP_CHANNEL_DOMAIN_INDEX` (`DOMAIN`),
  KEY `BFP_CHANNEL_UUID_INDEX` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `bfp_channel_daily_stat` (
  `ID` int(12) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `CHANNEL_ID` int(12) NOT NULL,
  `STATS_DAY` date NOT NULL,
  `VIEWS` int(14) NOT NULL COMMENT 'PV',
  `CLICKS` int(14) DEFAULT NULL COMMENT '点击量',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BFP_CHANNEL_STAT_PK_INDEX` (`CHANNEL_ID`,`STATS_DAY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `stats_ad_daily`
ADD COLUMN `CPM_VIEW_NO`  int(11) NOT NULL DEFAULT 0 COMMENT 'CPM展示' AFTER `CPS_TOTAL_PRICE`,
ADD COLUMN `CPM_PUB_COMMISSION`  decimal(16,5) NOT NULL DEFAULT 0 COMMENT 'CPM站长佣金，即我们发放给站长的佣金' AFTER `CPM_VIEW_NO`,
ADD COLUMN `CPM_TOTAL_COMMISSION`  decimal(16,5) NOT NULL DEFAULT 0 COMMENT 'CPM佣金总额，即我们得到的佣金' AFTER `CPM_PUB_COMMISSION`;

ALTER TABLE `stats_order_daily`
ADD COLUMN `CPM_VIEW_NO`  int(11) NOT NULL DEFAULT 0 COMMENT 'CPM展示' AFTER `CPS_TOTAL_PRICE`,
ADD COLUMN `CPM_PUB_COMMISSION`  decimal(16,5) NOT NULL DEFAULT 0 COMMENT 'CPM站长佣金，即我们发放给站长的佣金' AFTER `CPM_VIEW_NO`,
ADD COLUMN `CPM_TOTAL_COMMISSION`  decimal(16,5) NOT NULL DEFAULT 0 COMMENT 'CPM佣金总额，即我们得到的佣金' AFTER `CPM_PUB_COMMISSION`;

ALTER TABLE  `stats_ad_daily` ADD  `CPC_VIEW_NO` INT NOT NULL DEFAULT  '0' COMMENT 'CPC广告的展示数' AFTER  `CLICKS` ;
ALTER TABLE  `stats_ad_daily` ADD  `CPM_CLICK_NO` INT NOT NULL DEFAULT  '0' COMMENT 'CPM广告的点击数' AFTER  `CPM_VIEW_NO` ;
ALTER TABLE  `stats_order_daily` ADD  `CPC_VIEW_NO` INT NOT NULL DEFAULT  '0' COMMENT 'CPC广告的展示数' AFTER  `CLICKS` ;
ALTER TABLE  `stats_order_daily` ADD  `CPM_CLICK_NO` INT NOT NULL DEFAULT  '0' COMMENT 'CPM广告的点击数' AFTER  `CPM_VIEW_NO` ;


ALTER TABLE  `buzzads`.`ad_order` DROP `NETWORK`, DROP `BID_TYPE`;
ALTER TABLE  `buzzads`.`ad_order` 
ADD COLUMN `ADS_TYPE` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0-均匀投放, 1-加速投放',
ADD COLUMN `CHANNELS` text DEFAULT NULL COMMENT '投放媒体列表',
ADD COLUMN `FREQUENCY_CAP` int(10) NOT NULL DEFAULT 0 COMMENT '广告向单个用户展示的次数频次上限';

ALTER TABLE `bfp_channel`
ADD COLUMN `STATUS` tinyint(1) NULL DEFAULT NULL AFTER `CHANNEL_TYPE`,
ADD COLUMN `OPERATE_REASON`  varchar(256) DEFAULT NULL COMMENT 'media状态变更原因（仅冻结和删除）' AFTER `AD_THUMB`;


ALTER TABLE  `buzzads`.`advertiser_account`
ADD COLUMN `SECRET`  binary(16) DEFAULT NULL;

ALTER TABLE `buzzads`.`bfp_channel`
ADD COLUMN `STYLE` tinyint(2) NOT NULL DEFAULT 0 COMMENT '0-120*120 99-UNKNOWN';


CREATE TABLE `ads_campaign_daybudget` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAMP_ID` int(11) NOT NULL,
  `BUDGET_DAY` date NOT NULL,
  `BUDGET` int(8) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CAMP_DAY_INDEX` (`CAMP_ID`,`BUDGET_DAY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `bfp_channel` CHANGE `STYLE` `STYLE` TINYINT( 2 ) NOT NULL DEFAULT '1' COMMENT '0-120*120 1-UNKNOWN';


