package com.buzzinate.buzzads.user;

import java.io.Serializable;

/**
 * 
 * @author zyeming
 *
 */
public class UserBase implements Serializable {

    private static final long serialVersionUID = -749319229080768280L;
    
    // Unique ID generated by the application.
    private int userID;
    // Name of the User
    private String name;
    // Login ID of the user
    private String loginID;
    // Password of the user
    private String password;
    // User's email address
    private String email;

    
    public UserBase() { }

    public UserBase(int userID, String name, String loginID, String password,
            String email) {
        super();
        this.userID = userID;
        this.name = name;
        this.loginID = loginID;
        this.password = password;
        this.email = email;
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLoginID() {
        return loginID;
    }

    public void setLoginID(String loginID) {
        this.loginID = loginID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getUserID() {
        return userID;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    
    @Override
    public String toString() {
        return "UserBase [userID=" + userID + ", name=" + name + ", loginID=" + loginID + 
                        ", password=" + password + ", email=" + email + "]";
    }

    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((email == null) ? 0 : email.hashCode());
        result = prime * result + ((loginID == null) ? 0 : loginID.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((password == null) ? 0 : password.hashCode());
        result = prime * result + userID;
        return result;
    }

    
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UserBase other = (UserBase) obj;
        if (email == null) {
            if (other.email != null)
                return false;
        } else if (!email.equals(other.email))
            return false;
        if (loginID == null) {
            if (other.loginID != null)
                return false;
        } else if (!loginID.equals(other.loginID))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        } else if (!password.equals(other.password))
            return false;
        if (userID != other.userID)
            return false;
        return true;
    }


}